const students={
  user1:{
    name:"palvi",
    email:"abc@gmail.com"
  },
  user2:{
    name:"grishma",
    email:"xyz@gmail.com"
  },
  user3:{
    name:"Harshita",
    email:"lmn@gmail.com"
  },
}
const techer={
    tech1:{
      name:"palvi",
      email:"abc@gmail.com"
    },
    tech2:{
      name:"grishma",
      email:"xyz@gmail.com"
    },
    tech3:{
      name:"Harshita",
      email:"lmn@gmail.com"
    },
  }
exports.students=students
exports.techer=techer